services:
  mongo:
    container_name: mongo
    image: docker.mirror.markant.com/mongo:4.4.2
    ports:
    - 27017:27017

  testapp:
    container_name: app
    image: docker.io/library/example-native-service:0.0.1-SNAPSHOT
    ports:
    - 8080:8081
